[package]
name = "fcv"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.19", features = ["derive"]}
env_logger = "0.11"
glam = "0.29"
log = "0.4"
pollster = "0.4"
wgpu = "23"
winit = "0.30"